/** Briefing field extracted by AI */
export interface BriefingField {
  label: string;
  value: string;
  icon?: string;
}

/** Question the client asked (explicitly or implicitly) */
export interface ClientQuestion {
  question: string;
  context?: string;
}

/** Question the professional should ask the client (missing info) */
export interface SuggestedQuestion {
  question: string;
  reason: string;
}

/** The structured output from the AI curation */
export interface CuratedBriefing {
  title: string;
  summary: string;
  fields: BriefingField[];
  clientQuestions: ClientQuestion[];
  suggestedQuestions: SuggestedQuestion[];
  originalInput: string;
}

/** Follow-up question generated by AI after initial input */
export interface FollowUpQuestion {
  id: string;
  question: string;
  reason: string;
}

/** User's answer to a follow-up question */
export interface FollowUpAnswer {
  questionId: string;
  question: string;
  answer: string;
}

/** Attachment (image/file) from the client */
export interface BriefingAttachment {
  id: string;
  file: File;
  preview: string; // data URL for images
  type: 'image' | 'file';
}

/** AI-generated seed question stored on a link */
export interface SeedQuestion {
  id: string;
  question: string;
  reason: string;
}

/** App state machine */
export type AppPhase =
  | 'idle'
  | 'processing'
  | 'follow-up'
  | 'processing-final'
  | 'result'
  | 'error';
